/**
 * Generates the seed that reproduces the design's own scenario as real rows.
 *
 * The Innsikt screen prints ARBEIDSMILJØINDEKS 61, "−3 siden i fjor", and
 * "5 forsvarlig · 4 følges opp · 2 høy risiko". Those numbers must come out of the
 * database, not out of the component — the rule is that a value which does not exist
 * in the schema is never rendered as though it does. So the fixture is built backwards
 * from the design: choose answer distributions whose computed indices are exactly the
 * eleven the statutory report prints, and let results_summary derive the rest.
 *
 * With 28 respondents x 3 statements = 84 answers per factor and index = (v-1)*25, a
 * target T needs sum(v-1) = round(T*84/25); splitting that sum across two adjacent
 * scale points hits every one of the eleven targets exactly, in both years.
 *
 * Group sizes are the design's too: Drift 8, Prosjekt 9, Verksted 8, Administrasjon 3
 * = 28 of 34 employees, which is the "28 av 34 — 82 %" the report states. Administrasjon
 * at 3 is deliberately below k, so the k-anonymity path is exercised by the fixture
 * rather than only by tests.
 */
const FACTORS = [
  ['ytring', 41, 48], ['mengde', 44, 53], ['motstrid', 52, 58], ['kontakt', 57, 57],
  ['emosjon', 58, 59], ['leder', 64, 69], ['medvirk', 66, 63], ['integritet', 69, 70],
  ['rolle', 71, 73], ['kollega', 76, 75], ['mening', 78, 74],
]
const GROUPS = [['Drift', 8], ['Prosjekt', 9], ['Verksted', 8], ['Administrasjon', 3]]
const RESPONDENTS = GROUPS.reduce((a, g) => a + g[1], 0)
const EMPLOYEES = 34
const SLOTS = RESPONDENTS * 3

const cfg = (yearIdx) =>
  FACTORS.map(([key, y26, y25]) => {
    const target = yearIdx === 2026 ? y26 : y25
    const S = Math.round((target * SLOTS) / 25)
    const q = Math.floor(S / SLOTS), r = S % SLOTS
    return `('${key}',${r},${q + 2},${q + 1})`
  }).join(',')

const ORG = '00000000-0000-4000-8000-000000000001'
const R26 = '00000000-0000-4000-8000-000000000002'
const R25 = '00000000-0000-4000-8000-000000000012'
const M26 = '00000000-0000-4000-8000-000000000003'
const M25 = '00000000-0000-4000-8000-000000000013'

const answersFor = (round, yearIdx) => `
with cfg(factor_key, hi_count, hi_value, lo_value) as (values ${cfg(yearIdx)}),
resp as (select id, row_number() over (order by id) as seq from app.responses where round_id = '${round}'),
slots as (select r.id, r.seq, o.ordinal from resp r cross join (values (1),(2),(3)) as o(ordinal)),
numbered as (
  select c.factor_key, s.id, s.ordinal, c.hi_count, c.hi_value, c.lo_value,
         row_number() over (partition by c.factor_key order by s.seq, s.ordinal) as n
  from cfg c cross join slots s)
insert into app.answers (response_id, factor_key, ordinal, value)
select id, factor_key, ordinal, case when n <= hi_count then hi_value else lo_value end
from numbered;`

const groupRows = GROUPS.map(([n], i) => `('${n}',${i + 1})`).join(',')
const respRows = GROUPS.flatMap(([n, c]) => Array.from({ length: c }, () => `'${n}'`)).join(',')

console.log(`-- generated by scripts/seed/design-fixture.mjs — do not edit by hand
delete from app.measurements where org_id = '${ORG}';
delete from app.employees   where org_id = '${ORG}';
delete from app.groups      where org_id = '${ORG}';

update app.organizations set name='Nordvik Anlegg AS', org_number='924118742',
       employee_count=${EMPLOYEES}, threshold=5 where id='${ORG}';

insert into app.groups (org_id, name, sort_order)
select '${ORG}', g.name, g.ord from (values ${groupRows}) as g(name, ord);

insert into app.employees (org_id, group_id, full_name, email)
select '${ORG}', grp.id, 'Ansatt ' || n, 'ansatt' || n || '@nordvik.example'
from generate_series(1, ${EMPLOYEES}) n
left join lateral (
  select id from app.groups where org_id='${ORG}'
  order by sort_order offset ((n-1) % ${GROUPS.length}) limit 1) grp on true;

insert into app.measurements (id, org_id, kind, year, label) values
  ('${M25}','${ORG}','grunnlinje',2025,'Grunnlinje 2025'),
  ('${M26}','${ORG}','grunnlinje',2026,'Grunnlinje 2026');

insert into app.rounds (id, org_id, measurement_id, status, opens_at, closes_at, frozen_at) values
  ('${R25}','${ORG}','${M25}','lukket', now()-interval '400 days', now()-interval '380 days', now()-interval '380 days'),
  ('${R26}','${ORG}','${M26}','lukket', now()-interval '15 days',  now()-interval '8 days',   now()-interval '8 days');

insert into app.round_factors (org_id, round_id, factor_key)
select '${ORG}', r.id, f.key from app.rounds r cross join app.factors f
where r.id in ('${R25}','${R26}');

-- responses carry the group and nothing else that could identify anyone
insert into app.responses (org_id, round_id, group_id, submitted_hour)
select '${ORG}', r.round_id::uuid, g.id, date_trunc('hour', now() - (r.days || ' days')::interval)
from (values ('${R25}','385'), ('${R26}','10')) as r(round_id, days)
cross join lateral (
  select grp.id from unnest(array[${respRows}]) as want(name)
  join app.groups grp on grp.org_id='${ORG}' and grp.name = want.name) g;
${answersFor(R25, 2025)}
${answersFor(R26, 2026)}
select
  (select count(*) from app.responses where round_id='${R26}') as resp_2026,
  (select count(*) from app.responses where round_id='${R25}') as resp_2025,
  (select count(*) from app.answers a join app.responses r on r.id=a.response_id where r.round_id='${R26}') as ans_2026;`)
