/**
 * Generates types/i18n-keys.ts — a union of every `namespace.key` in
 * messages/no.json. `no` is the source language, so a key missing there is a
 * compile error at the call site rather than a blank string at runtime.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const source = JSON.parse(readFileSync('messages/no.json', 'utf8')) as Record<
  string,
  Record<string, string>
>

const keys: string[] = []
for (const [namespace, entries] of Object.entries(source)) {
  if (typeof entries !== 'object' || entries === null) continue
  for (const key of Object.keys(entries)) keys.push(`${namespace}.${key}`)
}
keys.sort()

const body = `// GENERATED by scripts/gen-i18n-types.ts — do not edit by hand.
// Source of truth: messages/no.json (${keys.length} keys).

export type MessageKey =
${keys.map((k) => `  | '${k}'`).join('\n')}

export type Namespace = ${[...new Set(Object.keys(source))]
  .sort()
  .map((n) => `'${n}'`)
  .join(' | ')}
`

writeFileSync('types/i18n-keys.ts', body)
console.log(`wrote types/i18n-keys.ts (${keys.length} keys)`)
